finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path,include
from hdps import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('hdps/',include('hdps.urls')),
]

finalproject/hdps/urls.py
from django.contrib import admin
from django.urls import path
from hdps import views
from django.contrib.auth import views as auth_views
from django.contrib.auth import get_user_model
app_name = 'hdps'
urlpatterns = [
path('login/',auth_views.LoginView.as_view(template_name='signin.html'),name='login'),
path('signup/',views.SignUp.as_view(),name='user_signup'),
path('logout/',auth_views.LogoutView.as_view(),name='logout'),
path('profile/',views.ProfileForm.as_view(),name='profile_form'),
path('<int:pk>/',views.ProfileDetailView.as_view(),name='profile-detail'),
path('<int:pk>/update',views.ProfileUpdateView.as_view(),name='profile-update'),
path('<int:pk>/profile/',views.ProfileForm.as_view(),name='profile_form'),
path('user_report_form/',views.userReportView,name='user-report-form'),
path('prediction/',views.predict,name='heart_prediction')
]

finalproject/hdps/models.py
from django.db import models
from django.conf import settings
from django.contrib import auth
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return '{} {}'.format(self.first_name,self.last_name)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key = True,on_delete=models.CASCADE)
    age = models.IntegerField(blank=True,null=True)
    birth_date = models.DateField(null=True, blank=True)
    phone_no = models.IntegerField()
    address = models.CharField(max_length=30, blank=True)
    profile_pic = models.ImageField(blank=True,null=True)

    def __str__(self):
        return " {} ".format(self.user)

    # def get_absolute_url(self):
    #     return reverse('hdps:profile-detail', kwargs={'pk': self.pk})


class UserReport(models.Model):
    SEX_CHOICES = [
        (1,'Male'),
        (0,'Female'),
        (0,'Others')
    ]
    CHEST_PAIN_CHOICES = [
        (1,'Typical Angina'),
        (2,'Atypical Angina'),
        (3,'Non-Anignal Pain'),
        (4,'Asymptotic')
    ]
    BLOOD_SUGAR_CHOICES = [
        (0,'Blood Sugar < 120mg/dl'),
        (1,'Blood Sugar > 120mg/dl')
    ]
    ECG_CHOICES = [
        (0,'Normal'),
        (1,'Having ST-T Wave Abromality'),
        (2,'Left Ventricular Hyperthrophy')
    ]
    EXERCISE_ANGINA_CHOICES = [
        (1,'Yes'),
        (0,'No')
    ]
    PEAK_ST_SEGMENT_CHOICES = [
        (1,'Upsloping'),
        (2,'Flat'),
        (3,'Downsloping')
    ]
    THAL_CHOICES=[
        (3,'Normal'),
        (6,'Fixed Defect'),
        (7,'Reversible Defect')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    age = models.IntegerField()
    sex = models.IntegerField(choices= SEX_CHOICES)
    cp = models.IntegerField(choices= CHEST_PAIN_CHOICES)
    restbps = models.IntegerField()
    chol = models.IntegerField()
    fbs = models.IntegerField(choices=BLOOD_SUGAR_CHOICES)
    ecg = models.IntegerField(choices=ECG_CHOICES)
    heart_rate = models.IntegerField()
    ex_in_angina = models.IntegerField(choices = EXERCISE_ANGINA_CHOICES)
    st_depression_in_exercise = models.FloatField()
    peak_st_segment = models.IntegerField(choices=PEAK_ST_SEGMENT_CHOICES)
    vessels_by_flourosopy = models.FloatField()
    thal = models.IntegerField(choices=THAL_CHOICES)
    date_time = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return "{}".format(self.user)

def post_save_user_model_reciever(sender,instance,created,*args,**kwargs):
    if created:
        try:
            Profile.objects.create(user=instance)
        except:
            pass
post_save.connect(post_save_user_model_reciever,sender=settings.AUTH_USER_MODEL)

finalproject/hdps/forms.py
from django.contrib.auth  import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib import auth
from hdps.models import Profile
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length = 256)
    last_name = forms.CharField(max_length = 256)
    class Meta:
        fields = ('username','first_name','last_name','email','password1','password2')
        model = get_user_model()

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            self.fields['username'].label = 'USER NAME'
            self.fields['first_name'].label = 'FIRST NAME'
            self.fields['last_name'].label = 'LAST NAME'
            self.fields['email'].label = 'EMAIL'
            self.fields['password1'].label = 'PASSWORD'
            self.fields['password2'].label = 'CONFORM PASSWORD'

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        # fields = '__all__
        exclude = ['user']

class UserReportForm(forms.Form):
    SEX_CHOICES = [
        (1,'Male'),
        (0,'Female'),
        (0,'Others')
    ]
    CHEST_PAIN_CHOICES = [
        (1,'Typical Angina'),
        (2,'Atypical Angina'),
        (3,'Non-Anignal Pain'),
        (4,'Asymptotic')
    ]
    BLOOD_SUGAR_CHOICES = [
        (0,'Blood Sugar < 120mg/dl'),
        (1,'Blood Sugar > 120mg/dl')
    ]
    ECG_CHOICES = [
        (0,'Normal'),
        (1,'Having ST-T Wave Abromality'),
        (2,'Left Ventricular Hyperthrophy')
    ]
    EXERCISE_ANGINA_CHOICES = [
        (1,'Yes'),
        (0,'No')
    ]
    PEAK_ST_SEGMENT_CHOICES = [
        (1,'Upsloping'),
        (2,'Flat'),
        (3,'Downsloping')
    ]
    THAL_CHOICES=[
        (3,'Normal'),
        (6,'Fixed Defect'),
        (7,'Reversible Defect')
    ]
    age = forms.IntegerField()
    sex = forms.ChoiceField(choices= SEX_CHOICES)
    cp = forms.ChoiceField(choices= CHEST_PAIN_CHOICES)
    # restbps = forms.IntegerField()
    chol = forms.IntegerField()
    fbs = forms.ChoiceField(choices=BLOOD_SUGAR_CHOICES)
    # ecg = forms.IntegerField(choices=ECG_CHOICES)
    # heart_rate = forms.IntegerField()
    ex_in_angina = forms.ChoiceField(choices = EXERCISE_ANGINA_CHOICES)
    st_depression_in_exercise = forms.FloatField()
    peak_st_segment = forms.ChoiceField(choices=PEAK_ST_SEGMENT_CHOICES)
    vessels_by_flourosopy = forms.FloatField()
    thal = forms.ChoiceField(choices=THAL_CHOICES)

finalproject/hdps/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse_lazy,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.detail import DetailView,SingleObjectMixin
from django.views.generic.list import ListView
from hdps import forms
import openpyxl
from .models import Profile
from .forms import ProfileModelForm,SignUpForm,UserReportForm
from .models import UserReport
from hdps.apps import HdpsConfig
from sklearn.preprocessing import StandardScaler as ss
import numpy as np
# Create your views here.
class SignUp(CreateView):
    form_class = forms.SignUpForm
    success_url = reverse_lazy('hdps:login')
    template_name = 'signup.html'

class ProfileForm(LoginRequiredMixin,CreateView):
    form_class = forms.ProfileModelForm
    template_name = 'profile_form.html'

    def form_valid(self, form):
        fields = ['age','birth_date','phone_no','address','profile_pic']
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('hdps:profile-detail',kwargs={'pk':self.object.user.id})


class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profile_detail.html'

    def get_object(self):
        try:
            object = super().get_object()
        except:
            object = None
            return object
        return object



class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileModelForm
    template_name = 'profile_form.html'

    def get_object(self):
        id_ = self.request.user.id
        return super().get_object()

    def form_valid(self, form):
        fields = ['age','birth_date','phone_no','address','profile_pic']
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('hdps:profile-detail',kwargs={'pk':self.object.user.id})

#############################################################################################

def userReportView(request):
    if request.method == 'POST':
        form = UserReportForm(request.POST)
        if form.is_valid():
            user = request.user
            age = form.cleaned_data['age']
            sex = form.cleaned_data['sex']
            cp = form.cleaned_data['cp']
            chol = form.cleaned_data['chol']
            fbs = form.cleaned_data['fbs']
            ex_in_angina = form.cleaned_data['ex_in_angina']
            st_depression_in_exercise = form.cleaned_data['st_depression_in_exercise']
            peak_st_segment = form.cleaned_data['peak_st_segment']
            vessels_by_flourosopy = form.cleaned_data['vessels_by_flourosopy']
            thal = form.cleaned_data['thal']

            excel_file = request.FILES["excel_file"]
            wb = openpyxl.load_workbook(excel_file)
            worksheet = wb.active
            restbps = worksheet.cell(row=2,column=1).value
            ecg =  worksheet.cell(row=2,column=2).value
            heart_rate =  worksheet.cell(row=2,column=3).value
            u = UserReport(user=user,age=age,sex=sex,cp=cp,restbps=restbps,chol=chol,fbs=fbs,ecg=ecg,heart_rate=heart_rate,ex_in_angina=ex_in_angina,st_depression_in_exercise=st_depression_in_exercise,peak_st_segment=peak_st_segment,vessels_by_flourosopy=vessels_by_flourosopy,thal=thal)
            u.save()
            return HttpResponseRedirect(reverse('hdps:heart_prediction'))
    else:
        form =UserReportForm()
    return render(request,'report_form.html',{'form':form})
############################################################################################
def home(request):
    return render(request,'home.html')
##########################################################################################
def predict(request):
    data = UserReport.objects.filter(user=request.user).latest('date_time')
    print(data.age)
    reportData = np.array([data.age,data.sex,data.cp,data.restbps,data.chol,data.fbs,data.ecg,data.heart_rate,data.ex_in_angina,data.st_depression_in_exercise,data.peak_st_segment,data.vessels_by_flourosopy,data.thal])
    reportData = reportData.reshape(1,-1)
    sc = ss()
    trained_data = sc.fit_transform(HdpsConfig.trained_data)
    reportData = sc.transform(reportData)
    result = HdpsConfig.classifier.predict(reportData)
    if data.sex == 1:
        sex = 'MALE'
    else:
        sex= 'FEMALE'
    if data.ecg == 0:
        ecg_val = 'Normal'
    elif data.ecg == 1:
        ecg_val = 'ST-T Wave Abnormality'
    else:
        ecg_val = 'Left Ventricular Hyperthrophy'

    try:
        profile = Profile.objects.get(user = request.user)
    except:
        profile = None
    return render(request,'prediction_report.html',{'report_data':data,'result':result,'sex':sex,'profile':profile,'ecg_val':ecg_val})

finalproject/hdps/templates/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <title>HDPS</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel='stylesheet' href=" {% static 'css/home.css' %}" />
</head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{%url 'home'%}">HEART DISEASE PREDICTION SYSTEM</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{%url 'home'%}">Dashboard</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'hdps:profile-detail' request.user.id %}">Profile</a></li>
              <li><a href="{% url 'hdps:logout'%}">Log Out</a></li>
            {%else%}
              <li><a href="admin/">Admin</a></li>
            {% endif %}
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% if user.is_authenticated %}
          <ul class="nav nav-sidebar">
            <li><a href="{%url 'hdps:user-report-form' %}">CHECK HEART STATUS</a></li>
            <li><a href="#">REPORTS</a></li>
            <li><a href="#">ANALYTICS</a></li>
            <li><a href="#">EXPORT</a></li>
          </ul>
          {% else %}
          <ul class="nav nav-sidebar">
            <li class="{% block overview-link %}active{% endblock %}"><a href="{%url 'home'%}">Overview <span class="sr-only">(current)</span></a></li>
            <li class="{% block register-link%}{%endblock%}"><a href="{% url 'hdps:user_signup'  %}">USER REGISTER</a></li>
            <li class="{% block login-link%}{%endblock%}"><a href="{% url 'hdps:login' %}">USER LOGIN</a></li>
            <!-- <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li> -->
          </ul>
          {% endif %}
        </div>

        {% block body_block %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{% static 'images/image_1.jpg' %}" width="400" height="400" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{% static 'images/img_2.jpg' %} " width="400" height="400" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{% static 'images/img_3.jpg' %}" width="400" height="400" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="{% static 'images/img_4.jpg' %}" width="400" height="400" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>
          {% endblock %}

        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"></script>')</script>
    <!-- <script src="../../dist/js/bootstrap.min.js"></script> -->
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <!-- <script src="../../assets/js/vendor/holder.min.js"></script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>
</html>

finalproject/hdps/templates/prediction_report.html
{% extends 'home.html' %}
{% load staticfiles %}
{% block body_block %}
<link rel='stylesheet' href=" {% static 'css/prediction_report.css' %}" />
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <!-- <div class="card pmd-card"> -->
                                    <!-- <div class="card-body"> -->

                                        <!-- Basic Information -->
                                        <div class="details-tab">
                                            <div class="d-flex flex-row align-items-center mb-2">
                                                <h2 class="card-title media-body">Patient Information</h2>
                                            </div>
                                            <hr>
                                            <div class="row view-basic-card">
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">First Name</label>
                                                        <p class="pmd-list-title">{{user.first_name}}</p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Last Name</label>
                                                        <p class="pmd-list-title">{{user.last_name}}</p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Middle Name</label>
                                                        <p class="pmd-list-title"> </p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Phone</label>
                                                        <p class="pmd-list-title"><a href="#" title="">{{profile.phone_no}}</a></p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Personal Email</label>
                                                        <p class="pmd-list-title"><a href="#" title="">{{user.email}}</a></p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Date of Birt</label>
                                                        <p class="pmd-list-title">{{profile.birth_date}} </p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Gender</label>
                                                        <p class="pmd-list-title">{{sex}}</p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Address</label>
                                                        <p class="pmd-list-title">{{profile.address}}</p>
                                                    </div>
                                                </div>

                                        </div><br><br>

                                        <!-- Employee Information -->
                                        <div class="details-tab">
                                            <div class="d-flex flex-row align-items-center mb-2">
                                                <h2 class="card-title media-body">Patient Health Detail</h2>

                                            </div>
                                            <hr>
                                            <!-- View Card -->
                                            <div class="row view-employee-card">
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Blood Pressure</label>
                                                        <p class="pmd-list-title">{{report_data.restbps}} mmHg</p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Cholestrol </label>
                                                        <p class="pmd-list-title">{{report_data.chol}} mmol/L</p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">ECG </label>
                                                        <p class="pmd-list-title">{{ecg_val}}</p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Heart Rate</label>
                                                        <p class="pmd-list-title">{{report_data.heart_rate}} bpm</p>
                                                    </div>
                                                    <div class="col-12 col-md-6 col-lg-3">
                                                        <label class="pmd-list-subtitle">Heart Status</label>
                                                        {% if result == 0%}
                                                          <p class="pmd-list-title" style='color:green'>NORMAL</p>
                                                        {% else %}
                                                        <p class="pmd-list-title" style='color:red'>ABNORMAL</p>
                                                        {%endif%}                                                   </div>

                                                </div>

                                        <!-- </div> -->




</div>
{% endblock %}

finalproject/hdps/templates/profile_detail.html
{% extends 'home.html' %}
{% block body_block %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  {% if object is not None%}
  <h1 class="page-header">User Profile : {{object}}</h1>
      <ul>

          <li> {{object.user.first_name}}</li>
          <li> {{object.user.last_name}}</li>
          <li> {{object.user.email}}</li>
          <li> {{object.birth_date}}</li>
          <li> {{object.phone_no}}</li>
            <li> {{object.address}}</li>

      </ul>
      <a href="update"  <button type="button" class="btn btn-primary">Update Profile</button>
        {%else%}
        <a href="profile/"  <button type="button" class="btn btn-primary">Create Profile</button>
        {%endif%}
  </div>
{% endblock %}

finalproject/hdps/templates/profile_form.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block body_block %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1> Fill Profile Detail </h1>
    <form method='POST' enctype="multipart/form-data">
      {% csrf_token %}
      {% if user.is_authenticated %}
      <h1> {{ user.get_full_name }}</h1>
        {% endif %}
      {% bootstrap_form form %}
    <input class="btn btn-default" type="submit" value="Submit">
    </form>
    </div>
    {% endblock %}

finalproject/hdps/templates/report_form.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block body_block %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1> Fill Patient Detail </h1>
    <form method='POST' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="file" class="btn btn-default" name="excel_file" title='Upload Excel File'><br>
    <input class="btn btn-default" type="submit" value="Submit">
    </form>
    </div>
    {% endblock %}

finalproject/hdps/templates/signin.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block login-link%}active{%endblock%}
{% block body_block %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header">SIGN IN</h1>
    <form method='POST'>
      {% csrf_token %}
      {% bootstrap_form form %}
    <input class="btn btn-default" type="submit" value="Submit">
    </form>
    </div>
    {% endblock %}

finalproject/hdps/templates/signup.html
<!DOCTYPE html>
{% extends 'home.html' %}
{% load bootstrap4 %}
{% block body_block %}
{% block register-link %}active{% endblock %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header">SIGN UP</h1>
    <form method='POST'>
      {% csrf_token %}
      {% bootstrap_form form %}
    <input class="btn btn-default" type="submit" value="Submit">
    </form>
    </div>
    {% endblock %}